version: "3.9"

services:

  db:
    image: postgres:16
    container_name: pfa-db
    restart: always
    environment:
      POSTGRES_DB: pfa_db
      POSTGRES_USER: pfa_user
      POSTGRES_PASSWORD: pfa_pass
    ports:
      - "5432:5432"
    volumes:
      - pfa_db_data:/var/lib/postgresql/data
    networks:
      - pfa-net


  authservice:
    build:
      context: ./Authservice
    container_name: authservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=pfa_db;Username=pfa_user;Password=pfa_pass"
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pfa-net


  userprofileservice:
    build:
      context: ./Userprofileservice
    container_name: userprofileservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=pfa_db;Username=pfa_user;Password=pfa_pass"
    depends_on:
      - db
    ports:
      - "8083:8080"
    networks:
      - pfa-net


  messagingservice:
    build:
      context: ./Messagingservice
    container_name: messagingservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=pfa_db;Username=pfa_user;Password=pfa_pass"
    depends_on:
      - db
    ports:
      - "8084:8080"
    networks:
      - pfa-net


  projectservice:
    build:
      context: ./Projectservice
    container_name: projectservice
    environment:
      DATABASE_URL: "postgresql://pfa_user:pfa_pass@db:5432/pfa_db?serverVersion=16&charset=utf8"
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - pfa-net


  matching-spring:
    build:
      context: ./Matching-spring
    container_name: matching-spring
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/pfa_db"
      SPRING_DATASOURCE_USERNAME: "pfa_user"
      SPRING_DATASOURCE_PASSWORD: "pfa_pass"
      PYTHON_MATCHING_URL: "http://matching-python:8000"
    depends_on:
      - db
      - matching-python
    ports:
      - "8082:8082"
    networks:
      - pfa-net


  matching-python:
    build:
      context: ./Matching-python
    container_name: matching-python
    ports:
      - "8000:8000"
    networks:
      - pfa-net


networks:
  pfa-net:

volumes:
  pfa_db_data:

